[package]
name = "open-edc"
version = "0.1.0"
authors = [
  "Paul Sanders <paul@pbsdatasolutions.com>",
]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.81"
axum = "0.7.5"
chrono = { version = "0.4.37", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive"] }
dotenvy = "0.15.7"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "postgres", "chrono"] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
http-body-util = "0.1.1"
mime = "0.3.17"
tower = { version = "0.4.13", features = ["util"] }
