version: "3"

services:
  open-edc:
    image: open-edc:dev
    build:
      context: .
    container_name: open-edc
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - MONGO_INITDB_DATABASE=open_edc
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_PORT=27017
      - MONGO_HOST=db
      - SECRET_KEY=secret
    volumes:
      - type: bind
        source: .
        target: /open-edc
        read_only: false
  db:
    image: mongo:7.0
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=open_edc
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    expose:
      - 27017
    ports:
      - "27017:27017"

volumes:
  db-data:

networks:
  achievaim:
