version: "3"

services:
  db:
    image: postgres:16
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "open_edc"
    volumes:
      - db-data:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:7.2
    expose:
      - 6379
    ports:
      - 6379:6379
    command: valkey-server --requirepass valkeypassword

volumes:
  db-data:

networks:
  open_edc_network:
