services:
  open-edc:
    image: open-edc:dev
    container_name: open-edc
    depends_on:
      - db
      - valkey
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - SERVER_URL=0.0.0.0
      - DATABASE_ADDRESS=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=test_password
      - DATABASE_URL=postgresql://postgres:test_password@db:5432/open_edc # For sqlx
      - VALKEY_ADDRESS=valkey
      - VALKEY_PASSWORD=valkeypassword
  db:
    image: postgres:16
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "open_edc"
    volumes:
      - db-data:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:7.2
    expose:
      - 6379
    ports:
      - 6379:6379
    command: valkey-server --requirepass valkeypassword

volumes:
  db-data:

networks:
  open_edc_network:
